//! Message types for RustyCode
//!
//! Provides types for conversations with LLMs, including structured content
//! support for vision capabilities.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt;

use crate::SessionId;

/// Image source for vision content blocks
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ImageSource {
    /// Source type: "base64", "url", or "file"
    #[serde(rename = "type")]
    pub source_type: String,

    /// Media type: "image/png", "image/jpeg", "image/gif", "image/webp"
    pub media_type: String,

    /// Image data (base64 string for base64 type, URL for url type, file path for file type)
    pub data: String,
}

impl ImageSource {
    /// Create a base64-encoded image source
    pub fn base64(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self {
            source_type: "base64".to_string(),
            media_type: media_type.into(),
            data: data.into(),
        }
    }

    /// Create a URL-based image source
    pub fn url(url: impl Into<String>, media_type: impl Into<String>) -> Self {
        Self {
            source_type: "url".to_string(),
            media_type: media_type.into(),
            data: url.into(),
        }
    }

    /// Create a file-based image source
    pub fn file(path: impl Into<String>, media_type: impl Into<String>) -> Self {
        Self {
            source_type: "file".to_string(),
            media_type: media_type.into(),
            data: path.into(),
        }
    }
}

/// Cache control for prompt caching
///
/// Enables caching of content blocks across API calls to reduce token costs.
/// Cached content is billed at a lower rate and can be reused in subsequent requests.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
pub struct CacheControl {
    #[serde(rename = "type")]
    pub cache_type: CacheType,
}

/// Type of caching to use
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[non_exhaustive]
pub enum CacheType {
    /// Ephemeral caching (default)
    /// Content is cached for 5 minutes and can be reused across requests
    Ephemeral,
    /// Persistent caching (when available)
    /// Content is cached for longer periods (requires enterprise tier)
    #[serde(rename = "persistent")]
    Persistent,
}

impl CacheControl {
    /// Create ephemeral cache control (5-minute TTL)
    pub fn ephemeral() -> Self {
        Self {
            cache_type: CacheType::Ephemeral,
        }
    }

    /// Create persistent cache control (enterprise feature)
    pub fn persistent() -> Self {
        Self {
            cache_type: CacheType::Persistent,
        }
    }
}

impl Default for CacheControl {
    fn default() -> Self {
        Self::ephemeral()
    }
}

/// Content block for structured messages (Claude Messages API format)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum ContentBlock {
    /// Text content block
    #[serde(rename = "text")]
    Text {
        text: String,
        /// Cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },

    /// Image content block (vision support)
    #[serde(rename = "image")]
    Image {
        source: ImageSource,
        /// Cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<CacheControl>,
    },

    /// Tool use content block (function calling)
    #[serde(rename = "tool_use")]
    ToolUse {
        /// Unique identifier for this tool use
        id: String,
        /// Name of the tool/function being called
        name: String,
        /// Input parameters for the tool (as JSON object)
        input: serde_json::Value,
    },

    /// Thinking content block (extended thinking)
    ///
    /// Contains the model's internal reasoning process when extended thinking is enabled.
    /// This is automatically generated by Claude 4 models and provides transparency into
    /// the reasoning process.
    #[serde(rename = "thinking")]
    Thinking {
        /// The thinking/reasoning content
        thinking: String,
        /// Cryptographic signature for authentication
        signature: String,
    },

    /// Tool result content block (response to a tool_use)
    /// Must be sent as part of a user message following an assistant message with tool_use blocks.
    #[serde(rename = "tool_result")]
    ToolResult {
        /// The tool_use_id from the corresponding tool_use block
        tool_use_id: String,
        /// The result content (can be text or other content)
        content: String,
        /// Whether the tool execution resulted in an error
        #[serde(skip_serializing_if = "std::ops::Not::not")]
        is_error: bool,
    },
}

impl ContentBlock {
    /// Create a text content block
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text {
            text: text.into(),
            cache_control: None,
        }
    }

    /// Create a tool result content block
    pub fn tool_result(tool_use_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self::ToolResult {
            tool_use_id: tool_use_id.into(),
            content: content.into(),
            is_error: false,
        }
    }

    /// Create a tool result content block indicating an error
    pub fn tool_error(tool_use_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self::ToolResult {
            tool_use_id: tool_use_id.into(),
            content: content.into(),
            is_error: true,
        }
    }

    /// Create a text content block with caching enabled
    pub fn cached_text(text: impl Into<String>, cache_type: CacheType) -> Self {
        Self::Text {
            text: text.into(),
            cache_control: Some(CacheControl { cache_type }),
        }
    }

    /// Create an image content block
    pub fn image(source: ImageSource) -> Self {
        Self::Image {
            source,
            cache_control: None,
        }
    }

    /// Create an image content block with caching enabled
    pub fn cached_image(source: ImageSource, cache_type: CacheType) -> Self {
        Self::Image {
            source,
            cache_control: Some(CacheControl { cache_type }),
        }
    }

    /// Set cache control for this content block
    pub fn with_cache(mut self, cache_type: CacheType) -> Self {
        match &mut self {
            Self::Text { cache_control, .. } => {
                *cache_control = Some(CacheControl { cache_type });
            }
            Self::Image { cache_control, .. } => {
                *cache_control = Some(CacheControl { cache_type });
            }
            Self::ToolUse { .. } | Self::Thinking { .. } | Self::ToolResult { .. } => {
                // ToolUse, Thinking, and ToolResult blocks don't support caching - no-op
            }
        }
        self
    }

    /// Create a tool use content block
    pub fn tool_use(
        id: impl Into<String>,
        name: impl Into<String>,
        input: serde_json::Value,
    ) -> Self {
        Self::ToolUse {
            id: id.into(),
            name: name.into(),
            input,
        }
    }

    /// Create a thinking content block (extended thinking)
    pub fn thinking(thinking: impl Into<String>, signature: impl Into<String>) -> Self {
        Self::Thinking {
            thinking: thinking.into(),
            signature: signature.into(),
        }
    }

    /// Check if this is a text block
    pub fn is_text(&self) -> bool {
        matches!(self, Self::Text { .. })
    }

    /// Check if this is an image block
    pub fn is_image(&self) -> bool {
        matches!(self, Self::Image { .. })
    }

    /// Check if this is a tool use block
    pub fn is_tool_use(&self) -> bool {
        matches!(self, Self::ToolUse { .. })
    }

    /// Check if this is a thinking block
    pub fn is_thinking(&self) -> bool {
        matches!(self, Self::Thinking { .. })
    }

    /// Check if this block has caching enabled
    pub fn is_cached(&self) -> bool {
        match self {
            Self::Text { cache_control, .. } => cache_control.is_some(),
            Self::Image { cache_control, .. } => cache_control.is_some(),
            Self::ToolUse { .. } | Self::Thinking { .. } | Self::ToolResult { .. } => false,
        }
    }
}

/// Message content supporting both simple strings and structured blocks
///
/// # Examples
///
/// ```rust
/// use rustycode_protocol::{MessageContent, ContentBlock, ImageSource};
///
/// // Simple text content (backward compatible)
/// let simple = MessageContent::simple("Hello, world!");
///
/// // Structured content with text block
/// let structured = MessageContent::text_block("Hello, world!");
///
/// // Structured content with text and image
/// let with_image = MessageContent::text_and_image(
///     "What's in this image?",
///     ImageSource::url("https://example.com/image.jpg", "image/jpeg")
/// );
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(untagged)]
#[non_exhaustive]
pub enum MessageContent {
    /// Simple string content (backward compatible)
    Simple(String),

    /// Structured content blocks (Claude Messages API format)
    Blocks(Vec<ContentBlock>),
}

impl MessageContent {
    /// Create simple text content (backward compatible, serializes as string)
    pub fn simple(text: impl Into<String>) -> Self {
        Self::Simple(text.into())
    }

    /// Create structured content with a single text block (serializes as array with type field)
    ///
    /// Note: This creates a different serialization format than `simple()`.
    /// Use `simple()` for backward compatibility with existing APIs.
    pub fn text_block(text: impl Into<String>) -> Self {
        Self::Blocks(vec![ContentBlock::text(text)])
    }

    /// Create structured content with a cached text block
    ///
    /// Enables prompt caching for the text content, reducing costs for repetitive prompts.
    ///
    /// # Example
    ///
    /// ```ignore
    /// use rustycode_protocol::{MessageContent, CacheType};
    ///
    /// let cached = MessageContent::cached_text_block(
    ///     "You are a helpful assistant.",
    ///     CacheType::Ephemeral
    /// );
    /// ```
    pub fn cached_text_block(text: impl Into<String>, cache_type: CacheType) -> Self {
        Self::Blocks(vec![ContentBlock::cached_text(text, cache_type)])
    }

    /// Create structured content with multiple blocks
    pub fn blocks(blocks: Vec<ContentBlock>) -> Self {
        Self::Blocks(blocks)
    }

    /// Create content with both text and an image
    pub fn text_and_image(text: impl Into<String>, image_source: ImageSource) -> Self {
        Self::Blocks(vec![
            ContentBlock::text(text),
            ContentBlock::image(image_source),
        ])
    }

    /// Get the plain text representation (for backward compatibility)
    pub fn as_text(&self) -> String {
        match self {
            Self::Simple(text) => text.clone(),
            Self::Blocks(blocks) => blocks
                .iter()
                .map(|b| match b {
                    ContentBlock::Text { text, .. } => text.clone(),
                    ContentBlock::Image { .. } => "[Image]".to_string(),
                    ContentBlock::ToolUse { name, id, .. } => {
                        format!("[Tool use: {} ({})]", name, id)
                    }
                    ContentBlock::Thinking { .. } => "[Thinking]".to_string(),
                    ContentBlock::ToolResult {
                        content, is_error, ..
                    } => {
                        if *is_error {
                            format!("[Tool error: {}]", content)
                        } else {
                            content.clone()
                        }
                    }
                })
                .collect::<Vec<_>>()
                .join("\n"),
        }
    }

    /// Alias for as_text() - more convenient method name
    pub fn to_text(&self) -> String {
        self.as_text()
    }

    /// Check if content contains images
    pub fn has_images(&self) -> bool {
        match self {
            Self::Simple(_) => false,
            Self::Blocks(blocks) => blocks
                .iter()
                .any(|b| matches!(b, ContentBlock::Image { .. })),
        }
    }

    /// Get the length of the content in characters
    pub fn len(&self) -> usize {
        match self {
            Self::Simple(text) => text.len(),
            Self::Blocks(blocks) => blocks
                .iter()
                .map(|b| match b {
                    ContentBlock::Text { text, .. } => text.len(),
                    ContentBlock::Image { .. } => 7, // "[Image]" placeholder length
                    ContentBlock::ToolUse { .. } => 9, // "[Tool use]" placeholder length
                    ContentBlock::Thinking { .. } => 10, // "[Thinking]" placeholder length
                    ContentBlock::ToolResult { .. } => 12, // "[Tool result]" placeholder length
                })
                .sum(),
        }
    }

    /// Check if content is empty
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Convert to &str if simple content, or empty string for blocks
    /// Note: For blocks, this returns an empty string - use as_text() for full content
    pub fn as_str(&self) -> &str {
        match self {
            Self::Simple(text) => text.as_str(),
            Self::Blocks(_) => "", // Blocks need special handling - use as_text() instead
        }
    }

    /// Check if content contains a substring
    pub fn contains(&self, pattern: &str) -> bool {
        self.as_text().contains(pattern)
    }

    /// Check if this is simple (non-block) content
    pub fn is_simple(&self) -> bool {
        matches!(self, Self::Simple(_))
    }

    /// Check if this is block content
    pub fn is_blocks(&self) -> bool {
        matches!(self, Self::Blocks(_))
    }

    /// Get the simple text if this is Simple content, or None if blocks
    pub fn as_simple_str(&self) -> Option<&str> {
        match self {
            Self::Simple(text) => Some(text.as_str()),
            Self::Blocks(_) => None,
        }
    }
}

impl From<String> for MessageContent {
    fn from(text: String) -> Self {
        Self::Simple(text)
    }
}

impl From<&str> for MessageContent {
    fn from(text: &str) -> Self {
        Self::Simple(text.to_string())
    }
}

impl fmt::Display for MessageContent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Simple(text) => write!(f, "{}", text),
            Self::Blocks(blocks) => {
                for (i, block) in blocks.iter().enumerate() {
                    if i > 0 {
                        writeln!(f)?;
                    }
                    match block {
                        ContentBlock::Text { text, .. } => write!(f, "{}", text)?,
                        ContentBlock::Image { source, .. } => {
                            write!(f, "[Image: {} {}]", source.media_type, source.source_type)?;
                        }
                        ContentBlock::ToolUse { name, id, .. } => {
                            write!(f, "[Tool use: {} ({})]", name, id)?;
                        }
                        ContentBlock::Thinking { .. } => {
                            write!(f, "[Thinking]")?;
                        }
                        ContentBlock::ToolResult {
                            tool_use_id,
                            is_error,
                            ..
                        } => {
                            write!(
                                f,
                                "[Tool result: {}{}]",
                                tool_use_id,
                                if *is_error { " (error)" } else { "" }
                            )?;
                        }
                    }
                }
                Ok(())
            }
        }
    }
}

/// Metadata controlling message visibility for different audiences.
///
/// Inspired by goose's MessageMetadata pattern. Controls whether a message
/// is shown in the UI (user-visible) or included in the agent's context
/// window (agent-visible).
///
/// # Example
///
/// ```rust
/// use rustycode_protocol::MessageMetadata;
///
/// // Agent-only message (system prompt, internal reasoning)
/// let meta = MessageMetadata::agent_only();
/// assert!(!meta.user_visible);
/// assert!(meta.agent_visible);
///
/// // Default: visible to both
/// let default = MessageMetadata::default();
/// assert!(default.user_visible);
/// assert!(default.agent_visible);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Copy)]
pub struct MessageMetadata {
    /// Whether to show this message in the user-facing UI
    #[serde(default = "default_true")]
    pub user_visible: bool,
    /// Whether to include this message in the agent's context window
    #[serde(default = "default_true")]
    pub agent_visible: bool,
}

fn default_true() -> bool {
    true
}

impl Default for MessageMetadata {
    fn default() -> Self {
        Self {
            user_visible: true,
            agent_visible: true,
        }
    }
}

impl MessageMetadata {
    /// Visible to both user and agent (default)
    pub fn visible() -> Self {
        Self::default()
    }

    /// Visible only to the agent (not shown in UI)
    pub fn agent_only() -> Self {
        Self {
            user_visible: false,
            agent_visible: true,
        }
    }

    /// Visible only to the user (not in agent context)
    pub fn user_only() -> Self {
        Self {
            user_visible: true,
            agent_visible: false,
        }
    }

    /// Not visible to either (archived/hidden)
    pub fn invisible() -> Self {
        Self {
            user_visible: false,
            agent_visible: false,
        }
    }

    /// Builder: make agent-invisible
    pub fn with_agent_invisible(self) -> Self {
        Self {
            agent_visible: false,
            ..self
        }
    }

    /// Builder: make user-invisible
    pub fn with_user_invisible(self) -> Self {
        Self {
            user_visible: false,
            ..self
        }
    }

    /// Builder: make agent-visible
    pub fn with_agent_visible(self) -> Self {
        Self {
            agent_visible: true,
            ..self
        }
    }

    /// Builder: make user-visible
    pub fn with_user_visible(self) -> Self {
        Self {
            user_visible: true,
            ..self
        }
    }
}

/// A message in a conversation with the LLM.
///
/// Messages have a role (user, assistant, or system) and content,
/// along with a timestamp and visibility metadata for controlling
/// what's shown in different contexts.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// Role: "user", "assistant", or "system"
    pub role: String,
    /// Content of the message (supports both simple strings and structured blocks)
    pub content: MessageContent,
    /// When the message was created
    pub timestamp: DateTime<Utc>,
    /// Visibility metadata controlling who sees this message
    #[serde(default)]
    pub metadata: MessageMetadata,
}

impl Message {
    /// Create a user message
    pub fn user(content: impl Into<MessageContent>) -> Self {
        Self {
            role: "user".to_string(),
            content: content.into(),
            timestamp: Utc::now(),
            metadata: MessageMetadata::default(),
        }
    }

    /// Create an assistant message
    pub fn assistant(content: impl Into<MessageContent>) -> Self {
        Self {
            role: "assistant".to_string(),
            content: content.into(),
            timestamp: Utc::now(),
            metadata: MessageMetadata::default(),
        }
    }

    /// Create a system message
    pub fn system(content: impl Into<MessageContent>) -> Self {
        Self {
            role: "system".to_string(),
            content: content.into(),
            timestamp: Utc::now(),
            metadata: MessageMetadata::default(),
        }
    }

    /// Check if this is a user message
    pub fn is_user(&self) -> bool {
        self.role == "user"
    }

    /// Check if this is an assistant message
    pub fn is_assistant(&self) -> bool {
        self.role == "assistant"
    }

    /// Check if this is a system message
    pub fn is_system(&self) -> bool {
        self.role == "system"
    }

    /// Check if this message should be shown to users
    pub fn is_user_visible(&self) -> bool {
        self.metadata.user_visible
    }

    /// Check if this message should be in the agent's context
    pub fn is_agent_visible(&self) -> bool {
        self.metadata.agent_visible
    }

    /// Set visibility for this message (builder pattern)
    pub fn with_visibility(mut self, user_visible: bool, agent_visible: bool) -> Self {
        self.metadata = MessageMetadata {
            user_visible,
            agent_visible,
        };
        self
    }

    /// Make this message agent-only (hidden from UI)
    pub fn agent_only(mut self) -> Self {
        self.metadata = MessageMetadata::agent_only();
        self
    }

    /// Make this message user-only (excluded from agent context)
    pub fn user_only(mut self) -> Self {
        self.metadata = MessageMetadata::user_only();
        self
    }

    /// Set custom metadata (builder pattern)
    pub fn with_metadata(mut self, metadata: MessageMetadata) -> Self {
        self.metadata = metadata;
        self
    }
}

/// Conversation history for multi-turn interactions.
///
/// Tracks the exchange of messages between the user and the LLM,
/// providing context for subsequent interactions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    /// The session this conversation belongs to
    pub session_id: SessionId,
    /// Messages in the conversation
    pub messages: Vec<Message>,
    /// When the conversation was created
    pub created_at: DateTime<Utc>,
    /// When the conversation was last updated
    pub updated_at: DateTime<Utc>,
}

impl Conversation {
    /// Create a new conversation
    pub fn new(session_id: SessionId) -> Self {
        let now = Utc::now();
        Self {
            session_id,
            messages: Vec::new(),
            created_at: now,
            updated_at: now,
        }
    }

    /// Add a message to the conversation
    pub fn add_message(&mut self, message: Message) {
        self.messages.push(message);
        self.updated_at = Utc::now();
    }

    /// Get the number of messages in the conversation
    pub fn len(&self) -> usize {
        self.messages.len()
    }

    /// Check if the conversation is empty
    pub fn is_empty(&self) -> bool {
        self.messages.is_empty()
    }

    /// Get the last message, if any
    pub fn last_message(&self) -> Option<&Message> {
        self.messages.last()
    }

    /// Get all user messages
    pub fn user_messages(&self) -> Vec<&Message> {
        self.messages.iter().filter(|m| m.is_user()).collect()
    }

    /// Get all assistant messages
    pub fn assistant_messages(&self) -> Vec<&Message> {
        self.messages.iter().filter(|m| m.is_assistant()).collect()
    }

    /// Get messages visible to the user
    pub fn user_visible_messages(&self) -> Vec<&Message> {
        self.messages
            .iter()
            .filter(|m| m.is_user_visible())
            .collect()
    }

    /// Get messages visible to the agent
    pub fn agent_visible_messages(&self) -> Vec<&Message> {
        self.messages
            .iter()
            .filter(|m| m.is_agent_visible())
            .collect()
    }

    /// Get messages matching a custom filter
    pub fn filter_messages<F>(&self, predicate: F) -> Vec<&Message>
    where
        F: Fn(&Message) -> bool,
    {
        self.messages.iter().filter(|m| predicate(m)).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_image_source_creation() {
        let base64 = ImageSource::base64("image/png", "datahere");
        assert_eq!(base64.source_type, "base64");

        let url = ImageSource::url("https://example.com/img.jpg", "image/jpeg");
        assert_eq!(url.source_type, "url");

        let file = ImageSource::file("/path/to/img.png", "image/png");
        assert_eq!(file.source_type, "file");
    }

    #[test]
    fn test_message_content_simple() {
        let content = MessageContent::simple("Hello");
        assert!(content.is_simple());
        assert!(!content.is_blocks());
        assert_eq!(content.as_text(), "Hello");
    }

    #[test]
    fn test_message_content_with_image() {
        let content = MessageContent::text_and_image(
            "Look at this",
            ImageSource::url("https://example.com/img.jpg", "image/jpeg"),
        );
        assert!(content.is_blocks());
        assert!(content.has_images());
    }

    #[test]
    fn test_message_creation() {
        let msg = Message::user("Hello");
        assert!(msg.is_user());
        assert!(!msg.is_assistant());
        assert!(msg.is_user_visible());
        assert!(msg.is_agent_visible());

        let assistant = Message::assistant("Hi there");
        assert!(assistant.is_assistant());
        assert!(!assistant.is_user());
    }

    #[test]
    fn test_conversation() {
        let session_id = SessionId::new();
        let mut conv = Conversation::new(session_id);

        assert!(conv.is_empty());
        assert_eq!(conv.len(), 0);

        conv.add_message(Message::user("Hello"));
        conv.add_message(Message::assistant("Hi there"));

        assert_eq!(conv.len(), 2);
        assert_eq!(conv.user_messages().len(), 1);
        assert_eq!(conv.assistant_messages().len(), 1);
    }

    // ── MessageMetadata Tests ────────────────────────────────────────────────

    #[test]
    fn test_metadata_default_visible_to_both() {
        let meta = MessageMetadata::default();
        assert!(meta.user_visible);
        assert!(meta.agent_visible);
    }

    #[test]
    fn test_metadata_agent_only() {
        let meta = MessageMetadata::agent_only();
        assert!(!meta.user_visible);
        assert!(meta.agent_visible);
    }

    #[test]
    fn test_metadata_user_only() {
        let meta = MessageMetadata::user_only();
        assert!(meta.user_visible);
        assert!(!meta.agent_visible);
    }

    #[test]
    fn test_metadata_invisible() {
        let meta = MessageMetadata::invisible();
        assert!(!meta.user_visible);
        assert!(!meta.agent_visible);
    }

    #[test]
    fn test_metadata_builder_pattern() {
        let meta = MessageMetadata::default()
            .with_user_invisible()
            .with_agent_visible();
        assert!(!meta.user_visible);
        assert!(meta.agent_visible);

        let meta2 = MessageMetadata::agent_only().with_user_visible();
        assert!(meta2.user_visible);
        assert!(meta2.agent_visible);
    }

    #[test]
    fn test_message_with_visibility() {
        let msg = Message::system("System prompt").agent_only();
        assert!(!msg.is_user_visible());
        assert!(msg.is_agent_visible());
    }

    #[test]
    fn test_message_builder_visibility() {
        let msg = Message::assistant("Internal note").with_visibility(false, true);
        assert!(!msg.is_user_visible());
        assert!(msg.is_agent_visible());

        let msg2 = Message::user("UI hint").user_only();
        assert!(msg2.is_user_visible());
        assert!(!msg2.is_agent_visible());
    }

    #[test]
    fn test_conversation_visibility_filtering() {
        let session_id = SessionId::new();
        let mut conv = Conversation::new(session_id);

        conv.add_message(Message::system("sys").agent_only());
        conv.add_message(Message::user("hello"));
        conv.add_message(Message::assistant("hi").with_visibility(false, true));
        conv.add_message(Message::assistant("visible response"));

        // User-visible messages should exclude agent-only and visibility=false
        let user_vis = conv.user_visible_messages();
        assert_eq!(user_vis.len(), 2); // "hello" + "visible response"

        // Agent-visible messages should include all
        let agent_vis = conv.agent_visible_messages();
        assert_eq!(agent_vis.len(), 4); // all included
    }

    #[test]
    fn test_conversation_custom_filter() {
        let session_id = SessionId::new();
        let mut conv = Conversation::new(session_id);

        conv.add_message(Message::user("hello"));
        conv.add_message(Message::assistant("hi"));
        conv.add_message(Message::user("world"));

        let user_msgs = conv.filter_messages(|m| m.is_user());
        assert_eq!(user_msgs.len(), 2);
    }

    #[test]
    fn test_metadata_serialization_roundtrip() {
        let meta = MessageMetadata::agent_only();
        let json = serde_json::to_string(&meta).unwrap();
        let deserialized: MessageMetadata = serde_json::from_str(&json).unwrap();
        assert_eq!(meta, deserialized);
    }

    #[test]
    fn test_message_serialization_with_metadata() {
        let msg = Message::system("test").agent_only();
        let json = serde_json::to_string(&msg).unwrap();

        // Should contain metadata fields
        assert!(json.contains("user_visible"));
        assert!(json.contains("agent_visible"));

        let deserialized: Message = serde_json::from_str(&json).unwrap();
        assert!(!deserialized.metadata.user_visible);
        assert!(deserialized.metadata.agent_visible);
    }
}
