//! GENERATED by scripts/update_models.py — DO NOT EDIT MANUALLY
//!
//! Model catalog auto-generated from LiteLLM's model_prices_and_context_window.json.
//! To refresh: python3 scripts/update_models.py
//!
//! Source: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json

/// A single model entry in the catalog.
#[derive(Debug, Clone, Copy, PartialEq)]
#[allow(clippy::struct_excessive_bools)]
pub struct ModelEntry {
    /// Model identifier (e.g., "claude-sonnet-4-6", "gpt-4o")
    pub id: &'static str,
    /// Provider identifier (e.g., "anthropic", "openai")
    pub provider: &'static str,
    /// Maximum context window in tokens
    pub context_window: usize,
    /// Maximum output tokens
    pub max_output: usize,
    /// Cost per 1M input tokens in USD
    pub input_cost_per_1m: f64,
    /// Cost per 1M output tokens in USD
    pub output_cost_per_1m: f64,
    /// Whether the model supports vision/image inputs
    pub supports_vision: bool,
    /// Whether the model supports tool/function calling
    pub supports_tools: bool,
    /// Whether the model is a reasoning model
    pub supports_reasoning: bool,
    /// Whether the model supports prompt caching
    pub supports_caching: bool,
}

/// Default context window when a model is not in the catalog.
pub const DEFAULT_CONTEXT_WINDOW: usize = 100_000;

/// Default max output tokens when not specified.
pub const DEFAULT_MAX_OUTPUT: usize = 4_096;

/// The full model catalog, sorted by provider then model id.
pub static MODEL_CATALOG: &[ModelEntry] = &[
    ModelEntry {
        id: "qwen-coder-plus",
        provider: "alibaba-cn",
        context_window: 128_000,
        max_output: 8_192,
        input_cost_per_1m: 1.0,
        output_cost_per_1m: 3.0,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "qwen-max",
        provider: "alibaba-cn",
        context_window: 128_000,
        max_output: 8_192,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 6.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "qwen-coder-plus",
        provider: "alibaba-global",
        context_window: 128_000,
        max_output: 8_192,
        input_cost_per_1m: 1.0,
        output_cost_per_1m: 3.0,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "qwen-max",
        provider: "alibaba-global",
        context_window: 128_000,
        max_output: 8_192,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 6.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "claude-haiku-4-5",
        provider: "anthropic",
        context_window: 200_000,
        max_output: 64_000,
        input_cost_per_1m: 1.0,
        output_cost_per_1m: 5.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "claude-opus-4-6",
        provider: "anthropic",
        context_window: 1_000_000,
        max_output: 128_000,
        input_cost_per_1m: 5.0,
        output_cost_per_1m: 25.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "claude-opus-4-7",
        provider: "anthropic",
        context_window: 1_000_000,
        max_output: 128_000,
        input_cost_per_1m: 5.0,
        output_cost_per_1m: 25.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "claude-sonnet-4-5",
        provider: "anthropic",
        context_window: 200_000,
        max_output: 64_000,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "claude-sonnet-4-6",
        provider: "anthropic",
        context_window: 1_000_000,
        max_output: 64_000,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4-turbo",
        provider: "azure",
        context_window: 128_000,
        max_output: 4_096,
        input_cost_per_1m: 10.0,
        output_cost_per_1m: 30.0,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gpt-4.1",
        provider: "azure",
        context_window: 1_047_576,
        max_output: 32_768,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 8.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4.1-mini",
        provider: "azure",
        context_window: 1_047_576,
        max_output: 32_768,
        input_cost_per_1m: 0.4,
        output_cost_per_1m: 1.6,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4.1-nano",
        provider: "azure",
        context_window: 1_047_576,
        max_output: 32_768,
        input_cost_per_1m: 0.1,
        output_cost_per_1m: 0.4,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4o",
        provider: "azure",
        context_window: 128_000,
        max_output: 16_384,
        input_cost_per_1m: 2.5,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.1",
        provider: "azure",
        context_window: 272_000,
        max_output: 128_000,
        input_cost_per_1m: 1.25,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.2",
        provider: "azure",
        context_window: 272_000,
        max_output: 128_000,
        input_cost_per_1m: 1.75,
        output_cost_per_1m: 14.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.4",
        provider: "azure",
        context_window: 1_050_000,
        max_output: 128_000,
        input_cost_per_1m: 2.5,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.5",
        provider: "azure",
        context_window: 1_050_000,
        max_output: 128_000,
        input_cost_per_1m: 5.0,
        output_cost_per_1m: 30.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "mistral-large-latest",
        provider: "azure",
        context_window: 32_000,
        max_output: 32_000,
        input_cost_per_1m: 8.0,
        output_cost_per_1m: 24.0,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "o1",
        provider: "azure",
        context_window: 200_000,
        max_output: 100_000,
        input_cost_per_1m: 15.0,
        output_cost_per_1m: 60.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "o1-mini",
        provider: "azure",
        context_window: 128_000,
        max_output: 65_536,
        input_cost_per_1m: 1.21,
        output_cost_per_1m: 4.84,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "o3",
        provider: "azure",
        context_window: 200_000,
        max_output: 100_000,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 8.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "o4-mini",
        provider: "azure",
        context_window: 200_000,
        max_output: 100_000,
        input_cost_per_1m: 1.1,
        output_cost_per_1m: 4.4,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "claude-sonnet-4-5",
        provider: "bedrock",
        context_window: 200_000,
        max_output: 64_000,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "claude-sonnet-4-6-copilot",
        provider: "copilot",
        context_window: 200_000,
        max_output: 16_384,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "gpt-5.4-copilot",
        provider: "copilot",
        context_window: 1_000_000,
        max_output: 32_768,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "gpt-5.5-copilot",
        provider: "copilot",
        context_window: 1_000_000,
        max_output: 32_768,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemini-2.0-flash",
        provider: "gemini",
        context_window: 1_048_576,
        max_output: 8_192,
        input_cost_per_1m: 0.1,
        output_cost_per_1m: 0.4,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gemini-2.5-flash",
        provider: "gemini",
        context_window: 1_048_576,
        max_output: 65_535,
        input_cost_per_1m: 0.3,
        output_cost_per_1m: 2.5,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gemini-2.5-pro",
        provider: "gemini",
        context_window: 1_048_576,
        max_output: 65_535,
        input_cost_per_1m: 1.25,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "llama-3.1-70b-versatile",
        provider: "groq",
        context_window: 128_000,
        max_output: 8_192,
        input_cost_per_1m: 0.59,
        output_cost_per_1m: 0.79,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "llama3-70b-8192",
        provider: "groq",
        context_window: 8_192,
        max_output: 8_192,
        input_cost_per_1m: 0.59,
        output_cost_per_1m: 0.79,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "kimi-k2",
        provider: "kimi-cn",
        context_window: 200_000,
        max_output: 8_192,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "kimi-latest",
        provider: "kimi-cn",
        context_window: 200_000,
        max_output: 8_192,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "kimi-k2",
        provider: "kimi-global",
        context_window: 200_000,
        max_output: 8_192,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "kimi-latest",
        provider: "kimi-global",
        context_window: 200_000,
        max_output: 8_192,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "functiongemma-270m",
        provider: "litert-lm",
        context_window: 4_096,
        max_output: 2_048,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemma-3n-e2b",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemma-3n-e4b",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemma-4-e2b-it",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemma-4-e4b-it",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemma3-1b",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "phi-4-mini",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "qwen2.5-1.5b",
        provider: "litert-lm",
        context_window: 8_192,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "codestral-latest",
        provider: "mistral",
        context_window: 32_000,
        max_output: 8_191,
        input_cost_per_1m: 1.0,
        output_cost_per_1m: 3.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "mistral-large-latest",
        provider: "mistral",
        context_window: 262_144,
        max_output: 262_144,
        input_cost_per_1m: 0.5,
        output_cost_per_1m: 1.5,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "mistral-medium-latest",
        provider: "mistral",
        context_window: 131_072,
        max_output: 131_072,
        input_cost_per_1m: 0.4,
        output_cost_per_1m: 2.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "mistral-small-latest",
        provider: "mistral",
        context_window: 131_072,
        max_output: 131_072,
        input_cost_per_1m: 0.06,
        output_cost_per_1m: 0.18,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "open-mistral-nemo",
        provider: "mistral",
        context_window: 128_000,
        max_output: 128_000,
        input_cost_per_1m: 0.3,
        output_cost_per_1m: 0.3,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "llama3",
        provider: "ollama",
        context_window: 128_000,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "mistral",
        provider: "ollama",
        context_window: 32_000,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "qwen2.5-coder",
        provider: "ollama",
        context_window: 32_768,
        max_output: 4_096,
        input_cost_per_1m: 0.0,
        output_cost_per_1m: 0.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "gpt-4-turbo",
        provider: "openai",
        context_window: 128_000,
        max_output: 4_096,
        input_cost_per_1m: 10.0,
        output_cost_per_1m: 30.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4.1",
        provider: "openai",
        context_window: 1_047_576,
        max_output: 32_768,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 8.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4.1-mini",
        provider: "openai",
        context_window: 1_047_576,
        max_output: 32_768,
        input_cost_per_1m: 0.4,
        output_cost_per_1m: 1.6,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4.1-nano",
        provider: "openai",
        context_window: 1_047_576,
        max_output: 32_768,
        input_cost_per_1m: 0.1,
        output_cost_per_1m: 0.4,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-4o",
        provider: "openai",
        context_window: 128_000,
        max_output: 16_384,
        input_cost_per_1m: 2.5,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.1",
        provider: "openai",
        context_window: 272_000,
        max_output: 128_000,
        input_cost_per_1m: 1.25,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.2",
        provider: "openai",
        context_window: 272_000,
        max_output: 128_000,
        input_cost_per_1m: 1.75,
        output_cost_per_1m: 14.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.4",
        provider: "openai",
        context_window: 1_050_000,
        max_output: 128_000,
        input_cost_per_1m: 2.5,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gpt-5.5",
        provider: "openai",
        context_window: 1_050_000,
        max_output: 128_000,
        input_cost_per_1m: 5.0,
        output_cost_per_1m: 30.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "o1",
        provider: "openai",
        context_window: 200_000,
        max_output: 100_000,
        input_cost_per_1m: 15.0,
        output_cost_per_1m: 60.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "o3",
        provider: "openai",
        context_window: 200_000,
        max_output: 100_000,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 8.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "o4-mini",
        provider: "openai",
        context_window: 200_000,
        max_output: 100_000,
        input_cost_per_1m: 1.1,
        output_cost_per_1m: 4.4,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "deepseek/deepseek-chat",
        provider: "openrouter",
        context_window: 65_536,
        max_output: 8_192,
        input_cost_per_1m: 0.14,
        output_cost_per_1m: 0.28,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "google/gemini-2.5-flash",
        provider: "openrouter",
        context_window: 1_048_576,
        max_output: 8_192,
        input_cost_per_1m: 0.3,
        output_cost_per_1m: 2.5,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "google/gemini-2.5-pro",
        provider: "openrouter",
        context_window: 1_048_576,
        max_output: 8_192,
        input_cost_per_1m: 1.25,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "openai/gpt-4o",
        provider: "openrouter",
        context_window: 128_000,
        max_output: 4_096,
        input_cost_per_1m: 2.5,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "openai/o3-mini",
        provider: "openrouter",
        context_window: 128_000,
        max_output: 65_536,
        input_cost_per_1m: 1.1,
        output_cost_per_1m: 4.4,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "sonar",
        provider: "perplexity",
        context_window: 128_000,
        max_output: 128_000,
        input_cost_per_1m: 1.0,
        output_cost_per_1m: 1.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "sonar-pro",
        provider: "perplexity",
        context_window: 200_000,
        max_output: 8_000,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "sonar-reasoning",
        provider: "perplexity",
        context_window: 128_000,
        max_output: 128_000,
        input_cost_per_1m: 1.0,
        output_cost_per_1m: 5.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "sonar-reasoning-pro",
        provider: "perplexity",
        context_window: 128_000,
        max_output: 128_000,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 8.0,
        supports_vision: false,
        supports_tools: false,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "gemini-2.5-flash",
        provider: "vertex",
        context_window: 1_048_576,
        max_output: 65_536,
        input_cost_per_1m: 0.3,
        output_cost_per_1m: 2.5,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "gemini-2.5-flash-lite",
        provider: "vertex",
        context_window: 1_048_576,
        max_output: 65_536,
        input_cost_per_1m: 0.1,
        output_cost_per_1m: 0.4,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: true,
    },
    ModelEntry {
        id: "gemini-2.5-pro",
        provider: "vertex",
        context_window: 1_048_576,
        max_output: 65_536,
        input_cost_per_1m: 1.25,
        output_cost_per_1m: 10.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: true,
    },
    ModelEntry {
        id: "glm-4.7-flash",
        provider: "zhipu",
        context_window: 128_000,
        max_output: 8_192,
        input_cost_per_1m: 0.1,
        output_cost_per_1m: 0.1,
        supports_vision: false,
        supports_tools: true,
        supports_reasoning: false,
        supports_caching: false,
    },
    ModelEntry {
        id: "glm-5",
        provider: "zhipu",
        context_window: 200_000,
        max_output: 16_384,
        input_cost_per_1m: 3.0,
        output_cost_per_1m: 15.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "glm-5-turbo",
        provider: "zhipu",
        context_window: 200_000,
        max_output: 16_384,
        input_cost_per_1m: 2.0,
        output_cost_per_1m: 8.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
    ModelEntry {
        id: "glm-5.1",
        provider: "zhipu",
        context_window: 200_000,
        max_output: 131_072,
        input_cost_per_1m: 5.0,
        output_cost_per_1m: 20.0,
        supports_vision: true,
        supports_tools: true,
        supports_reasoning: true,
        supports_caching: false,
    },
];

/// Iterate over all catalog entries.
pub fn catalog() -> impl Iterator<Item = &'static ModelEntry> {
    MODEL_CATALOG.iter()
}

/// Look up a model by its ID.
///
/// Uses a 3-tier matching strategy:
/// 1. Exact match on `id`
/// 2. Strip provider prefix (e.g., "zai-coding-plan/glm-5" → "glm-5")
/// 3. Prefix match (e.g., "claude-sonnet-4-6-20250514" matches "claude-sonnet-4-6")
pub fn lookup(model_id: &str) -> Option<&'static ModelEntry> {
    // 1. Exact match
    if let Some(entry) = MODEL_CATALOG.iter().find(|e| e.id == model_id) {
        return Some(entry);
    }

    // 2. Strip provider prefix (e.g., "zai-coding-plan/glm-5" → "glm-5")
    if let Some(short_id) = model_id.rsplit('/').next() {
        if short_id != model_id {
            if let Some(entry) = MODEL_CATALOG.iter().find(|e| e.id == short_id) {
                return Some(entry);
            }
        }
    }

    // 3. Prefix match (e.g., "claude-sonnet-4-6-20250514" matches "claude-sonnet-4-6")
    MODEL_CATALOG.iter().find(|e| model_id.starts_with(e.id))
}

/// Get context window for a model, or the default.
pub fn context_window_for_model(model_id: &str) -> usize {
    lookup(model_id).map_or(DEFAULT_CONTEXT_WINDOW, |e| e.context_window)
}

/// Get models for a specific provider.
pub fn models_for_provider(provider_id: &str) -> Vec<&'static ModelEntry> {
    MODEL_CATALOG
        .iter()
        .filter(|e| e.provider == provider_id)
        .collect()
}

/// Get all unique provider IDs in the catalog.
pub fn all_providers() -> Vec<&'static str> {
    let mut providers: Vec<&str> = MODEL_CATALOG.iter().map(|e| e.provider).collect();
    providers.sort_unstable();
    providers.dedup();
    providers
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_catalog_not_empty() {
        assert!(!MODEL_CATALOG.is_empty());
    }

    #[test]
    fn test_lookup_exact() {
        // gpt-4o exists in multiple providers (openai, azure); lookup returns the first match
        let entry = lookup("gpt-4o");
        assert!(entry.is_some());
        assert!(entry.unwrap().id == "gpt-4o");
    }

    #[test]
    fn test_lookup_anthropic() {
        let entry = lookup("claude-sonnet-4-6");
        assert!(entry.is_some());
        assert_eq!(entry.unwrap().provider, "anthropic");
    }

    #[test]
    fn test_lookup_with_date_suffix() {
        // "claude-sonnet-4-6-20250514" should match "claude-sonnet-4-6"
        let entry = lookup("claude-sonnet-4-6-20250514");
        assert!(entry.is_some());
        assert_eq!(entry.unwrap().id, "claude-sonnet-4-6");
    }

    #[test]
    fn test_lookup_with_provider_prefix() {
        let entry = lookup("zai-coding-plan/glm-5");
        assert!(entry.is_some());
        assert_eq!(entry.unwrap().id, "glm-5");
    }

    #[test]
    fn test_lookup_unknown_returns_none() {
        assert!(lookup("totally-unknown-model-xyz").is_none());
    }

    #[test]
    fn test_context_window_for_known_model() {
        let cw = context_window_for_model("gpt-4o");
        assert!(cw > 0);
        assert_ne!(cw, DEFAULT_CONTEXT_WINDOW);
    }

    #[test]
    fn test_context_window_for_unknown_model() {
        let cw = context_window_for_model("future-model-3000");
        assert_eq!(cw, DEFAULT_CONTEXT_WINDOW);
    }

    #[test]
    fn test_models_for_provider() {
        let anthropic = models_for_provider("anthropic");
        assert!(!anthropic.is_empty());
        assert!(anthropic.iter().all(|m| m.provider == "anthropic"));
    }

    #[test]
    fn test_all_providers() {
        let providers = all_providers();
        assert!(!providers.is_empty());
        assert!(providers.contains(&"openai"));
        assert!(providers.contains(&"anthropic"));
    }

    #[test]
    fn test_catalog_sorted_by_provider() {
        for window in MODEL_CATALOG.windows(2) {
            assert!(
                window[0].provider <= window[1].provider,
                "Catalog not sorted: {} ({}) should come before {} ({})",
                window[0].provider,
                window[0].id,
                window[1].provider,
                window[1].id,
            );
        }
    }

    #[test]
    fn test_no_duplicate_ids_within_provider() {
        let mut seen = std::collections::HashSet::new();
        for entry in MODEL_CATALOG {
            let key = (entry.provider, entry.id);
            assert!(
                seen.insert(key),
                "Duplicate model: {}/{}",
                entry.provider,
                entry.id,
            );
        }
    }

    #[test]
    fn test_custom_models_present() {
        // Zhipu
        assert!(lookup("glm-5.1").is_some());
        assert!(lookup("glm-5").is_some());
        // Copilot
        assert!(lookup("gpt-5.5-copilot").is_some());
        // Ollama
        assert!(lookup("llama3").is_some());
        // LiteRT-LM
        assert!(lookup("gemma-4-e2b-it").is_some());
    }

    #[test]
    fn test_kimi_models_present() {
        let kimi_cn = models_for_provider("kimi-cn");
        assert!(!kimi_cn.is_empty());
        let kimi_global = models_for_provider("kimi-global");
        assert!(!kimi_global.is_empty());
    }
}
