#![allow(clippy::expect_used)] // build scripts panic on env/IO failure by convention

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let agents_dir = Path::new(&crate_dir).join("agents");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");

    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<_> = fs::read_dir(&agents_dir)
        .expect("failed to read agents/ directory")
        .filter_map(Result::ok)
        .filter(|entry| entry.path().extension().is_some_and(|ext| ext == "md"))
        .collect();

    entries.sort_by_key(std::fs::DirEntry::file_name);

    let mut agent_entries = Vec::new();
    for entry in &entries {
        let filename = entry.file_name();
        let filename_str = filename.to_string_lossy();
        let agent_name = filename_str.strip_suffix(".md").unwrap_or(&filename_str);

        println!("cargo:rerun-if-changed=agents/{filename_str}");

        agent_entries.push((agent_name.to_string(), filename_str.to_string()));
    }

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — DO NOT EDIT\n\n");
    output.push_str(
        "/// Returns all embedded agent definitions as (name, markdown_content) pairs.\n",
    );
    output.push_str("pub fn embedded_agents() -> Vec<(&'static str, &'static str)> {\n");
    output.push_str("    vec![\n");

    for (agent_name, filename) in &agent_entries {
        let _ = writeln!(
            output,
            "        (\"{agent_name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/agents/{filename}\"))),"
        );
    }

    output.push_str("    ]\n");
    output.push_str("}\n");

    let out_path = Path::new(&out_dir).join("embedded_agents.rs");
    fs::write(&out_path, &output).expect("failed to write embedded_agents.rs");
}
