[package]
name = "rustycode-shared-runtime"
version = "0.5.3"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { workspace = true }
futures = { workspace = true }
num_cpus = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }

[lints]
workspace = true

