[package]
name = "rustycode-tools-api"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow.workspace = true
lru.workspace = true
parking_lot.workspace = true
regex.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
tracing.workspace = true
rustycode-protocol = { path = "../rustycode-protocol" }
schemars = "1.2.1"

[lints]
workspace = true

