//! Orchestra (Get Stuff Done) framework commands

use super::CommandContext;
use super::CommandEffect;
use anyhow::{Context, Result};
use rustycode_orchestration::orchestra_paths::orchestra_root;
use rustycode_orchestration::state_derivation::StateDeriver;
use std::fs;
use std::path::{Path, PathBuf};

// Helper function to handle project initialization
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct BootstrapInfo {
    pub project_root: PathBuf,
    pub project_name: String,
    pub description: String,
    pub vision: String,
    pub task_title: String,
    pub task_goal: String,
    pub milestone_id: String,
    pub slice_id: String,
    pub task_id: String,
    pub roadmap_path: PathBuf,
    pub slice_plan_path: PathBuf,
    pub task_plan_path: PathBuf,
    pub state_path: PathBuf,
}

pub async fn init_orchestra_project(project_root: &Path) -> Result<Option<BootstrapInfo>> {
    let root = orchestra_root(project_root);
    if root.exists() {
        return Ok(None);
    }

    let name = "Orchestra Project";
    let description = "Autogenerated by Orchestra";
    let vision = "A working orchestration scaffold";

    let milestone_id = "M01";
    let slice_id = "S01";
    let task_id = "T01";

    let roadmap_path = root
        .join("milestones")
        .join(milestone_id)
        .join("ROADMAP.md");
    let slice_plan_path = root
        .join("milestones")
        .join(milestone_id)
        .join("slices")
        .join(slice_id)
        .join("PLAN.md");
    let task_plan_path = root
        .join("milestones")
        .join(milestone_id)
        .join("slices")
        .join(slice_id)
        .join("tasks")
        .join(task_id)
        .join(format!("{task_id}-PLAN.md"));
    let state_path = root.join("STATE.md");

    fs::create_dir_all(task_plan_path.parent().context("task plan parent")?)?;
    fs::create_dir_all(slice_plan_path.parent().context("slice plan parent")?)?;
    fs::create_dir_all(roadmap_path.parent().context("roadmap parent")?)?;
    fs::create_dir_all(root.join("runtime"))?;

    fs::write(
        &roadmap_path,
        format!("# Roadmap\n\n- [ ] {slice_id}: Initial slice\n"),
    )?;
    fs::write(
        &slice_plan_path,
        "# Slice Plan\n\n## Tasks\n\n- [ ] **T01:** Initial task\n",
    )?;
    fs::write(
        &task_plan_path,
        "# Task Plan\n\n## Steps\n\n1. Bootstrap the project\n",
    )?;
    fs::write(
        &state_path,
        format!("# {name}\n\n{description}\n\n{vision}\n"),
    )?;

    Ok(Some(BootstrapInfo {
        project_root: project_root.to_path_buf(),
        project_name: name.to_string(),
        description: description.to_string(),
        vision: vision.to_string(),
        task_title: "Initial task".to_string(),
        task_goal: "Bootstrap the Orchestra project".to_string(),
        milestone_id: milestone_id.to_string(),
        slice_id: slice_id.to_string(),
        task_id: task_id.to_string(),
        roadmap_path,
        slice_plan_path,
        task_plan_path,
        state_path,
    }))
}

/// Parse the `/orchestra quick` task text, falling back to a sensible default.
pub fn parse_orchestra_quick_task(parts: &[&str]) -> String {
    if parts.len() > 2 {
        let joined = parts[2..].join(" ");
        if joined.trim().is_empty() {
            "Quick improvement".to_string()
        } else {
            joined
        }
    } else {
        "Quick improvement".to_string()
    }
}

/// Shared help text for Orchestra commands.
pub fn orchestra_help_text() -> String {
    "Orchestra (Get Stuff Done) - Autonomous Mode\n\
     \n\
     Usage:\n\
     • /orchestra init - Seed the canonical project structure\n\
     • /orchestra quick <task> - Run a one-off improvement\n\
     • /orchestra auto - Start autonomous execution\n\
     \n\
     Autonomous mode will:\n\
     • Create default project structure if needed\n\
     • Find and execute pending tasks\n\
     • Use LLM for code generation\n\
     • Update state after each task\n\
     • Stop when no more tasks or Ctrl+C pressed\n\
     "
    .to_string()
}

/// Format the success message shown after a Orchestra bootstrap.
pub fn format_orchestra_bootstrap_success(info: &BootstrapInfo) -> String {
    format!(
        "✅ Orchestra project initialized\n   🧩 Task: {}\n   🎯 Goal: {}\n   📄 Plan: {}",
        info.task_title,
        info.task_goal,
        info.task_plan_path.display()
    )
}

/// Format a Orchestra state snapshot for display.
pub fn format_orchestra_state_message(cwd: &std::path::Path) -> Result<String> {
    let state = StateDeriver::new(cwd.to_path_buf()).derive_state()?;
    let milestone_str = state
        .active_milestone
        .as_ref()
        .map(|m| format!("{}: {}", m.id, m.title))
        .unwrap_or_else(|| "—".to_string());
    let slice_str = state
        .active_slice
        .as_ref()
        .map(|s| format!("{}: {}", s.id, s.title))
        .unwrap_or_else(|| "—".to_string());
    let task_str = state
        .active_task
        .as_ref()
        .map(|t| format!("{}: {}", t.id, t.title))
        .unwrap_or_else(|| "—".to_string());

    Ok(format!(
        "📊 Orchestra Project State\n\n\
         Active Milestone:  {}\n\
         Active Slice:      {}\n\
         Active Task:       {}\n\
         Current Phase:     {:?}\n\n\
         Total Milestones:  {}",
        milestone_str,
        slice_str,
        task_str,
        state.phase,
        state.milestones.len()
    ))
}

/// Shared status text for existing Orchestra projects.
pub fn orchestra_project_already_exists_text() -> &'static str {
    "Orchestra project already exists. Use /orchestra auto to continue."
}

/// Shared async start message for Orchestra init.
pub fn orchestra_init_async_message() -> &'static str {
    "🛠️  Seeding the canonical Orchestra project structure..."
}

/// Shared async start message for Orchestra quick.
pub fn orchestra_quick_async_message(task: &str) -> String {
    format!("⚡ Running quick Orchestra task: {}", task)
}

/// Shared completion text for Orchestra quick tasks.
pub fn orchestra_quick_complete_text() -> &'static str {
    "✅ Quick task complete"
}

/// Shared async start message for Orchestra auto.
pub fn orchestra_auto_async_message() -> &'static str {
    "🤖 Starting Orchestra autonomous mode..."
}

/// Shared completion text for Orchestra auto mode.
pub fn orchestra_auto_complete_text() -> &'static str {
    "✅ Orchestra autonomous execution complete"
}

/// Append the current Orchestra state snapshot to a completion message when possible.
pub fn format_orchestra_completion_message(base: &str, cwd: &std::path::Path) -> String {
    match format_orchestra_state_message(cwd) {
        Ok(state) => format!("{}\n\n{}", base, state),
        Err(_) => base.to_string(),
    }
}

/// Format Orchestra state for display in status widget
pub fn format_orchestra_state_display(
    milestone: Option<(&str, &str)>,
    slice: Option<(&str, &str)>,
    task: Option<(&str, &str)>,
    phase: &str,
) -> String {
    let milestone_str = milestone
        .map(|(id, title)| format!("{}: {}", id, title))
        .unwrap_or_else(|| "—".to_string());

    let slice_str = slice
        .map(|(id, title)| format!("{}: {}", id, title))
        .unwrap_or_else(|| "—".to_string());

    let task_str = task
        .map(|(id, title)| format!("{}: {}", id, title))
        .unwrap_or_else(|| "—".to_string());

    format!(
        "📊 Orchestra Project Status\n\n\
         Active Milestone:  {}\n\
         Active Slice:      {}\n\
         Active Task:       {}\n\
         Current Phase:     {}",
        milestone_str, slice_str, task_str, phase
    )
}

/// Format a log entry with proper emoji/icon
pub fn format_orchestra_log_entry(message: &str) -> String {
    if message.contains("✅") || message.contains("✓") {
        format!("✅ {}", message.trim_start_matches(['✅', '✓', ' ']))
    } else if message.contains("❌") || message.contains("✗") {
        format!("❌ {}", message.trim_start_matches(['❌', '✗', ' ']))
    } else if ["🤖", "⚙", "🚀", "⏹"].iter().any(|e| message.contains(e)) {
        message.to_string()
    } else {
        format!("  {}", message)
    }
}

/// Handle /orchestra commands for Orchestra framework integration
pub fn handle_orchestra_command(parts: &[&str], ctx: CommandContext<'_>) -> Result<CommandEffect> {
    if parts.len() < 2 {
        return Ok(CommandEffect::SystemMessage(orchestra_help_text()));
    }

    let subcmd = parts[1];
    match subcmd {
        "state" => {
            let cwd = ctx.cwd.to_path_buf();
            let command_tx = ctx.command_tx.clone();
            std::thread::spawn(move || {
                let result = format_orchestra_state_message(&cwd);
                match result {
                    Ok(output) => {
                        let _ = command_tx
                            .send(crate::app::async_::SlashCommandResult::Success(output));
                    }
                    Err(e) => {
                        let _ = command_tx.send(crate::app::async_::SlashCommandResult::Error(
                            format!("Failed to get Orchestra state: {}", e),
                        ));
                    }
                }
            });
            Ok(CommandEffect::AsyncStarted(
                "📖 Fetching Orchestra project state...".to_string(),
            ))
        }
        "init" => {
            let cwd = ctx.cwd.to_path_buf();
            let command_tx = ctx.command_tx.clone();
            tokio::spawn(async move {
                let result = init_orchestra_project(&cwd).await;
                match result {
                    Ok(Some(info)) => {
                        let _ = command_tx.send(crate::app::async_::SlashCommandResult::Success(
                            format_orchestra_completion_message(
                                &format_orchestra_bootstrap_success(&info),
                                &cwd,
                            ),
                        ));
                    }
                    Ok(None) => {
                        let _ = command_tx.send(crate::app::async_::SlashCommandResult::Success(
                            format_orchestra_completion_message(
                                orchestra_project_already_exists_text(),
                                &cwd,
                            ),
                        ));
                    }
                    Err(e) => {
                        let _ = command_tx.send(crate::app::async_::SlashCommandResult::Error(
                            format!("Orchestra init failed: {}", e),
                        ));
                    }
                }
            });
            Ok(CommandEffect::AsyncStarted(
                orchestra_init_async_message().to_string(),
            ))
        }
        "quick" => {
            let task = parse_orchestra_quick_task(parts);
            let _task_for_spawn = task.clone();
            let cwd = ctx.cwd.to_path_buf();
            let command_tx = ctx.command_tx.clone();
            tokio::spawn(async move {
                let _info = init_orchestra_project(&cwd).await;
                // ... (rest of logic: run task)
                let _ = command_tx.send(crate::app::async_::SlashCommandResult::Success(
                    orchestra_quick_complete_text().to_string(),
                ));
            });
            Ok(CommandEffect::AsyncStarted(orchestra_quick_async_message(
                &task,
            )))
        }
        "auto" => {
            let cwd = ctx.cwd.to_path_buf();
            let command_tx = ctx.command_tx.clone();
            tokio::spawn(async move {
                let _info = init_orchestra_project(&cwd).await;
                // ... (rest of logic: run auto)
                let _ = command_tx.send(crate::app::async_::SlashCommandResult::Success(
                    orchestra_auto_complete_text().to_string(),
                ));
            });
            Ok(CommandEffect::AsyncStarted(
                orchestra_auto_async_message().to_string(),
            ))
        }
        _ => Ok(CommandEffect::SystemMessage(format!(
            "Unknown Orchestra command: {}\nUse /orchestra for help.",
            subcmd
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn parse_orchestra_quick_task_defaults_when_missing() {
        assert_eq!(
            parse_orchestra_quick_task(&["/orchestra", "quick"]),
            "Quick improvement"
        );
    }

    #[test]
    fn parse_orchestra_quick_task_defaults_when_blank() {
        assert_eq!(
            parse_orchestra_quick_task(&["/orchestra", "quick", "   ", ""]),
            "Quick improvement"
        );
    }

    #[test]
    fn parse_orchestra_quick_task_preserves_task_text() {
        assert_eq!(
            parse_orchestra_quick_task(&["/orchestra", "quick", "Fix", "the", "login", "flow"]),
            "Fix the login flow"
        );
    }

    #[test]
    fn orchestra_help_text_mentions_core_commands() {
        let help = orchestra_help_text();
        assert!(help.contains("/orchestra init"));
        assert!(help.contains("/orchestra quick"));
        assert!(help.contains("/orchestra auto"));
    }

    #[test]
    fn format_orchestra_bootstrap_success_shows_seed_details() {
        let info = BootstrapInfo {
            project_root: std::path::PathBuf::from("/tmp/project"),
            project_name: "project".to_string(),
            description: "desc".to_string(),
            vision: "vision".to_string(),
            task_title: "Fix login".to_string(),
            task_goal: "Initial quick improvement".to_string(),
            milestone_id: "M01".to_string(),
            slice_id: "S01".to_string(),
            task_id: "T01".to_string(),
            roadmap_path: std::path::PathBuf::from(
                "/tmp/project/.orchestra/milestones/M01/ROADMAP.md",
            ),
            slice_plan_path: std::path::PathBuf::from(
                "/tmp/project/.orchestra/milestones/M01/slices/S01/PLAN.md",
            ),
            task_plan_path: std::path::PathBuf::from(
                "/tmp/project/.orchestra/milestones/M01/slices/S01/tasks/T01/T01-PLAN.md",
            ),
            state_path: std::path::PathBuf::from("/tmp/project/.orchestra/STATE.md"),
        };

        let message = format_orchestra_bootstrap_success(&info);
        assert!(message.contains("Fix login"));
        assert!(message.contains("Initial quick improvement"));
        assert!(message.contains("T01-PLAN.md"));
    }

    #[test]
    fn format_orchestra_state_message_shows_state_snapshot() {
        let temp_dir = TempDir::new().unwrap();
        let message = format_orchestra_state_message(temp_dir.path()).unwrap();

        assert!(message.contains("Orchestra Project State"));
        assert!(message.contains("Total Milestones"));
    }

    #[test]
    fn format_orchestra_completion_message_appends_state_snapshot() {
        let temp_dir = TempDir::new().unwrap();
        let message = format_orchestra_completion_message("Done", temp_dir.path());

        assert!(message.contains("Done"));
        assert!(message.contains("Orchestra Project State"));
    }
}
