use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use crate::orchestra_paths::orchestra_root;
use crate::state_derivation::StateDeriver;

#[derive(Debug, Clone)]
pub struct BootstrapInfo {
    pub project_root: PathBuf,
    pub project_name: String,
    pub description: String,
    pub vision: String,
    pub task_title: String,
    pub task_goal: String,
    pub milestone_id: String,
    pub slice_id: String,
    pub task_id: String,
    pub roadmap_path: PathBuf,
    pub slice_plan_path: PathBuf,
    pub task_plan_path: PathBuf,
    pub state_path: PathBuf,
}

pub struct OrchestraService;

impl OrchestraService {
    pub async fn bootstrap_default_if_needed(base_path: &Path) -> Result<Option<BootstrapInfo>> {
        if orchestra_root(base_path).exists() {
            return Ok(None);
        }
        Ok(Some(
            Self::init_project(
                base_path,
                "Orchestra Project",
                "Autogenerated by Orchestra",
                "A working orchestration scaffold",
            )
            .await?,
        ))
    }

    #[allow(clippy::unused_async)]
    pub async fn init_project(
        project_root: &Path,
        name: &str,
        description: &str,
        vision: &str,
    ) -> Result<BootstrapInfo> {
        let root = orchestra_root(project_root);
        let milestone_id = "M01";
        let slice_id = "S01";
        let task_id = "T01";

        let roadmap_path = root
            .join("milestones")
            .join(milestone_id)
            .join("ROADMAP.md");
        let slice_plan_path = root
            .join("milestones")
            .join(milestone_id)
            .join("slices")
            .join(slice_id)
            .join("PLAN.md");
        let task_plan_path = root
            .join("milestones")
            .join(milestone_id)
            .join("slices")
            .join(slice_id)
            .join("tasks")
            .join(task_id)
            .join(format!("{task_id}-PLAN.md"));
        let state_path = root.join("STATE.md");

        fs::create_dir_all(task_plan_path.parent().context("task plan parent")?)?;
        fs::create_dir_all(slice_plan_path.parent().context("slice plan parent")?)?;
        fs::create_dir_all(roadmap_path.parent().context("roadmap parent")?)?;
        fs::create_dir_all(root.join("runtime"))?;

        fs::write(
            &roadmap_path,
            format!("# Roadmap\n\n- [ ] {slice_id}: Initial slice\n"),
        )?;
        fs::write(
            &slice_plan_path,
            "# Slice Plan\n\n## Tasks\n\n- [ ] **T01:** Initial task\n",
        )?;
        fs::write(
            &task_plan_path,
            "# Task Plan\n\n## Steps\n\n1. Bootstrap the project\n",
        )?;
        fs::write(
            &state_path,
            format!("# {name}\n\n{description}\n\n{vision}\n"),
        )?;

        Ok(BootstrapInfo {
            project_root: project_root.to_path_buf(),
            project_name: name.to_string(),
            description: description.to_string(),
            vision: vision.to_string(),
            task_title: "Initial task".to_string(),
            task_goal: "Bootstrap the Orchestra project".to_string(),
            milestone_id: milestone_id.to_string(),
            slice_id: slice_id.to_string(),
            task_id: task_id.to_string(),
            roadmap_path,
            slice_plan_path,
            task_plan_path,
            state_path,
        })
    }

    pub async fn run_quick_task(
        project_root: PathBuf,
        task_description: String,
        _budget: f64,
    ) -> Result<Option<BootstrapInfo>> {
        if let Some(info) = Self::bootstrap_default_if_needed(&project_root).await? {
            return Ok(Some(info));
        }

        let deriver = StateDeriver::new(project_root.clone());
        let state = deriver.derive_state()?;
        let project_name = state
            .active_milestone
            .as_ref()
            .map_or_else(|| "Orchestra Project".to_string(), |m| m.title.clone());

        Ok(Some(BootstrapInfo {
            project_root,
            project_name,
            description: task_description.clone(),
            vision: task_description,
            task_title: "Quick task".to_string(),
            task_goal: "Execute a quick task".to_string(),
            milestone_id: "M01".to_string(),
            slice_id: "S01".to_string(),
            task_id: "T01".to_string(),
            roadmap_path: PathBuf::new(),
            slice_plan_path: PathBuf::new(),
            task_plan_path: PathBuf::new(),
            state_path: PathBuf::new(),
        }))
    }

    #[allow(clippy::unused_async)]
    pub async fn run_auto(
        _project_root: PathBuf,
        _budget: f64,
        _use_ast: bool,
    ) -> Result<Option<BootstrapInfo>> {
        // TODO: wire to orchestration executor
        // The original implementation used crate::orchestra_executor::OrchestraExecutor
        // which belongs to the orchestra crate. This will be wired when the executor
        // is moved or a bridge is created.
        Ok(None)
    }
}
